- hosts: all
  tasks:
    - name: ensure apache is at the latest version
      yum: name=httpd state=latest
      become: yes 
    - name: apache2 listen on port 8080
      lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
      become: yes
    - name: start httpd
      service:
          name: httpd
          state: started
      become: yes  
